from multiprocessing import Process
from datetime import datetime
import time
import os
global fp



def func(dir_list_var, job_cnt):
    for str_tmp in dir_list_var:
        fp = open("7z_result_{}.txt".format(job_cnt), 'a')
        func_status=os.system(str_tmp)
        if func_status !=0 :
            str_status='Fail: {}: {}
'.format(str_tmp,str(datetime.now()))
            fp.write(str_status)
        else :
            str_status='Success: {}: {}
'.format(str_tmp,str(datetime.now()))
            fp.write(str_status)
        fp.close()

if __name__ == '__main__':
    today =  datetime.today().strftime('%Y%m%d')

    file_path = "7z_command_" + today + ".txt"
    with open(file_path) as f :
        lines = f.readlines()

    raw_dir_list = [line.rstrip('
') for line in lines ]

    N = 60
    dir_cnt=len(raw_dir_list)
    div_dir_cnt=dir_cnt//N

    dir_list = [[] for _ in range(N)]

    i=0
    j=0

    for dir_tmp in raw_dir_list:
        if j < = div_dir_cnt :
           j=j+1
           dir_list[i].append(dir_tmp)
        else :
            i=i+1
            dir_list[i].append(dir_tmp)
            j=1


    p1 = Process(target=func, args=(dir_list[0],1))
    p2 = Process(target=func, args=(dir_list[1],2))
    p3 = Process(target=func, args=(dir_list[2],3))
    p4 = Process(target=func, args=(dir_list[3],4))
    p5 = Process(target=func, args=(dir_list[4],5))
    p6 = Process(target=func, args=(dir_list[5],6))
    p7 = Process(target=func, args=(dir_list[6],7))
    p8 = Process(target=func, args=(dir_list[7],8))
    p9 = Process(target=func, args=(dir_list[8],9))
    p10 = Process(target=func, args=(dir_list[9],10))
    p11 = Process(target=func, args=(dir_list[10],11))
    p12 = Process(target=func, args=(dir_list[11],12))
    p13 = Process(target=func, args=(dir_list[12],13))
    p14 = Process(target=func, args=(dir_list[13],14))
    p15 = Process(target=func, args=(dir_list[14],15))
    p16 = Process(target=func, args=(dir_list[15],16))
    p17 = Process(target=func, args=(dir_list[16],17))
    p18 = Process(target=func, args=(dir_list[17],18))
    p19 = Process(target=func, args=(dir_list[18],19))
    p20 = Process(target=func, args=(dir_list[19],20))
    p21 = Process(target=func, args=(dir_list[20],21))
    p22 = Process(target=func, args=(dir_list[21],22))
    p23 = Process(target=func, args=(dir_list[22],23))
    p24 = Process(target=func, args=(dir_list[23],24))
    p25 = Process(target=func, args=(dir_list[24],25))
    p26 = Process(target=func, args=(dir_list[25],26))
    p27 = Process(target=func, args=(dir_list[26],27))
    p28 = Process(target=func, args=(dir_list[27],28))
    p29 = Process(target=func, args=(dir_list[28],29))
    p30 = Process(target=func, args=(dir_list[29],30))
    p31 = Process(target=func, args=(dir_list[30],31))
    p32 = Process(target=func, args=(dir_list[31],32))
    p33 = Process(target=func, args=(dir_list[32],33))
    p34 = Process(target=func, args=(dir_list[33],34))
    p35 = Process(target=func, args=(dir_list[34],35))
    p36 = Process(target=func, args=(dir_list[35],36))
    p37 = Process(target=func, args=(dir_list[36],37))
    p38 = Process(target=func, args=(dir_list[37],38))
    p39 = Process(target=func, args=(dir_list[38],39))
    p40 = Process(target=func, args=(dir_list[39],40))
    p41 = Process(target=func, args=(dir_list[40],41))
    p42 = Process(target=func, args=(dir_list[41],42))
    p43 = Process(target=func, args=(dir_list[42],43))
    p44 = Process(target=func, args=(dir_list[43],44))
    p45 = Process(target=func, args=(dir_list[44],45))
    p46 = Process(target=func, args=(dir_list[45],46))
    p47 = Process(target=func, args=(dir_list[46],47))
    p48 = Process(target=func, args=(dir_list[47],48))
    p49 = Process(target=func, args=(dir_list[48],49))
    p50 = Process(target=func, args=(dir_list[49],50))
    p51 = Process(target=func, args=(dir_list[50],51))
    p52 = Process(target=func, args=(dir_list[51],52))
    p53 = Process(target=func, args=(dir_list[52],53))
    p54 = Process(target=func, args=(dir_list[53],54))
    p55 = Process(target=func, args=(dir_list[54],55))
    p56 = Process(target=func, args=(dir_list[55],56))
    p57 = Process(target=func, args=(dir_list[56],57))
    p58 = Process(target=func, args=(dir_list[57],58))
    p59 = Process(target=func, args=(dir_list[58],59))
    p60 = Process(target=func, args=(dir_list[59],60))


# start로 각 프로세스를 시작합니다. func1이 끝나지 않아도 func2가 실행됩니다.

    p1.start()
    p2.start()
    p3.start()
    p4.start()
    p5.start()
    p6.start()
    p7.start()
    p8.start()
    p9.start()
    p10.start()
    p11.start()
    p12.start()
    p13.start()
    p14.start()
    p15.start()
    p16.start()
    p17.start()
    p18.start()
    p19.start()
    p20.start()
    p21.start()
    p22.start()
    p23.start()
    p24.start()
    p25.start()
    p26.start()
    p27.start()
    p28.start()
    p29.start()
    p30.start()
    p31.start()
    p32.start()
    p33.start()
    p34.start()
    p35.start()
    p36.start()
    p37.start()
    p38.start()
    p39.start()
    p40.start()
    p41.start()
    p42.start()
    p43.start()
    p44.start()
    p45.start()
    p46.start()
    p47.start()
    p48.start()
    p49.start()
    p50.start()
    p51.start()
    p52.start()
    p53.start()
    p54.start()
    p55.start()
    p56.start()
    p57.start()
    p58.start()
    p59.start()
    p60.start()


# join으로 각 프로세스가 종료되길 기다립니다 p1.join()이 끝난 후 p2.join()을 수행합니다
    p1.join()
    p2.join()
    p3.join()
    p4.join()
    p5.join()
    p6.join()
    p7.join()
    p8.join()
    p9.join()
    p10.join()
    p11.join()
    p12.join()
    p13.join()
    p14.join()
    p15.join()
    p16.join()
    p17.join()
    p18.join()
    p19.join()
    p20.join()
    p21.join()
    p22.join()
    p23.join()
    p24.join()
    p25.join()
    p26.join()
    p27.join()
    p28.join()
    p29.join()
    p30.join()
    p31.join()
    p32.join()
    p33.join()
    p34.join()
    p35.join()
    p36.join()
    p37.join()
    p38.join()
    p39.join()
    p40.join()
    p41.join()
    p42.join()
    p43.join()
    p44.join()
    p45.join()
    p46.join()
    p47.join()
    p48.join()
    p49.join()
    p50.join()
    p51.join()
    p52.join()
    p53.join()
    p54.join()
    p55.join()
    p56.join()
    p57.join()
    p58.join()
    p59.join()
    p60.join()
